model_type: "vqc"
batch_size: 256
qlr: 0.001
clr: 0.00001
epochs: 100
embedding_qubits: 9

emulation_set: "swap"
noise: false
eps: 0.01

text:
  ansatz: "custom_v5"
  n: 1
  s: 1
  p: 1
  layers: 2
  curry: true
  spider: false

vision:
  layers: 4
  method: 'mlp' # 'amp' or 'pca' or 'mlp'

# dataset:
#   name: "aro"
#   labels: ["image", "pos_caption", "neg_caption"]
#   class: "modules.data_pipeline.datasets.ARODataset"
#   collate_fn: "modules.data_pipeline.datasets.aro_collate_fn"
#   eval_mapper: "modules.models.fusion.engine.aro_mapper"
#   eval_tasks: 
#     - "evaluate_text_choice"
#     - "compositional_diagnostic"

# splits:
#   train:
#     text_path: "data/aro/processed/train.pkl"
#     img_path: "data/aro/processed/image_embeddings.pt"
#   val:
#     text_path: "data/aro/processed/val.pkl"
#     img_path: "data/aro/processed/image_embeddings.pt"
#   test:
#     att:
#       text_path: "data/aro/processed/test_att.pkl"
#       img_path: "data/aro/processed/image_embeddings.pt"
#       task: "evaluate_text_choice"
#     rel:
#       text_path: "data/aro/processed/test_rel.pkl"
#       img_path: "data/aro/processed/image_embeddings.pt"
#       task: "evaluate_text_choice"

dataset:
  name: "svo-probes"
  labels: ["caption", "pos_image", "neg_image"]
  class: "modules.data_pipeline.datasets.SVODataset"
  collate_fn: "modules.data_pipeline.datasets.svo_collate_fn"
  eval_mapper: "modules.models.fusion.engine.svo_mapper"
  eval_tasks: 
    - "evaluate_image_choice"
    - "compositional_diagnostic"

splits:
  train:
    text_path: "data/svo-probes/processed/train.pkl"
    img_path: "data/svo-probes/processed/image_embeddings.pt"
  val:
    text_path: "data/svo-probes/processed/val.pkl"
    img_path: "data/svo-probes/processed/image_embeddings.pt"
  test:
    std:
      text_path: "data/svo-probes/processed/test.pkl"
      img_path: "data/svo-probes/processed/image_embeddings.pt"
      task: "evaluate_image_choice"
    swap:
      text_path: "data/svo-probes/processed/swap.pkl"
      img_path: "data/svo-probes/processed/image_embeddings.pt"
      task: "evaluate_text_choice"
